import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%DOBIUS_AGENT_HOOK_PORT%"=="" if defined DOBIUS_AGENT_HOOK_ENDPOINT if exist "%DOBIUS_AGENT_HOOK_ENDPOINT%" call "%DOBIUS_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%DOBIUS_AGENT_HOOK_TOKEN%"=="" if not "%DOBIUS_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      'if "%DOBIUS_AGENT_HOOK_PORT%"=="" exit /b 0',
      'if "%DOBIUS_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'if "%DOBIUS_PANE_KEY%"=="" exit /b 0',
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\dobius-dev\\agent-hooks" for /r "%APPDATA%\\dobius-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%DOBIUS_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\dobius\\agent-hooks" for /r "%APPDATA%\\dobius\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%DOBIUS_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set DOBIUS_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%DOBIUS_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    '__dobius_read_ancestor_var() {',
    '  __dobius_name="$1"',
    '  __dobius_pid="${PPID:-}"',
    '  while [ -n "$__dobius_pid" ] && [ "$__dobius_pid" != "0" ] && [ "$__dobius_pid" != "1" ]; do',
    '    __dobius_value=""',
    '    if [ -r "/proc/$__dobius_pid/environ" ]; then',
    '      __dobius_value=$(tr "\\000" "\\n" < "/proc/$__dobius_pid/environ" 2>/dev/null | sed -n "s/^${__dobius_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__dobius_value" ]; then',
    '      __dobius_value=$(ps eww -p "$__dobius_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__dobius_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__dobius_value" ]; then',
    '      printf "%s\\n" "$__dobius_value"',
    '      return 0',
    '    fi',
    '    __dobius_pid=$(ps -o ppid= -p "$__dobius_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__dobius_fill_from_ancestor() {',
    '  __dobius_name="$1"',
    '  case "$__dobius_name" in',
    '    DOBIUS_AGENT_HOOK_ENDPOINT) [ -z "${DOBIUS_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    DOBIUS_AGENT_HOOK_PORT) [ -z "${DOBIUS_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    DOBIUS_AGENT_HOOK_TOKEN) [ -z "${DOBIUS_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    DOBIUS_AGENT_HOOK_ENV) [ -z "${DOBIUS_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    DOBIUS_AGENT_HOOK_VERSION) [ -z "${DOBIUS_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    DOBIUS_PANE_KEY) [ -z "${DOBIUS_PANE_KEY:-}" ] || return 0 ;;',
    '    DOBIUS_TAB_ID) [ -z "${DOBIUS_TAB_ID:-}" ] || return 0 ;;',
    '    DOBIUS_WORKTREE_ID) [ -z "${DOBIUS_WORKTREE_ID:-}" ] || return 0 ;;',
    '    DOBIUS_AGENT_LAUNCH_TOKEN) [ -z "${DOBIUS_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __dobius_value=$(__dobius_read_ancestor_var "$__dobius_name") || return 0',
    '  [ -n "$__dobius_value" ] && export "$__dobius_name=$__dobius_value"',
    '}',
    '__dobius_endpoint_value() {',
    '  __dobius_endpoint_name="$1"',
    '  __dobius_endpoint_path="$2"',
    '  sed -n "s/^${__dobius_endpoint_name}=//p" "$__dobius_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__dobius_fill_from_endpoint_file() {',
    '  __dobius_endpoint_path="$1"',
    '  [ -r "$__dobius_endpoint_path" ] || return 0',
    '  __dobius_endpoint_port=$(__dobius_endpoint_value DOBIUS_AGENT_HOOK_PORT "$__dobius_endpoint_path")',
    '  if [ -n "${DOBIUS_AGENT_HOOK_PORT:-}" ] && [ -n "$__dobius_endpoint_port" ] && [ "$__dobius_endpoint_port" != "$DOBIUS_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __dobius_endpoint_name in DOBIUS_AGENT_HOOK_PORT DOBIUS_AGENT_HOOK_TOKEN DOBIUS_AGENT_HOOK_ENV DOBIUS_AGENT_HOOK_VERSION; do',
    '    eval "__dobius_current=\\${$__dobius_endpoint_name:-}"',
    '    [ -z "$__dobius_current" ] || continue',
    '    __dobius_endpoint_value=$(__dobius_endpoint_value "$__dobius_endpoint_name" "$__dobius_endpoint_path")',
    '    [ -n "$__dobius_endpoint_value" ] && export "$__dobius_endpoint_name=$__dobius_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Dobius pane/hook metadata, so recover it before posting.',
    'for __dobius_name in DOBIUS_AGENT_HOOK_ENDPOINT DOBIUS_AGENT_HOOK_PORT DOBIUS_AGENT_HOOK_TOKEN DOBIUS_AGENT_HOOK_ENV DOBIUS_AGENT_HOOK_VERSION DOBIUS_PANE_KEY DOBIUS_TAB_ID DOBIUS_WORKTREE_ID DOBIUS_AGENT_LAUNCH_TOKEN; do',
    '  __dobius_fill_from_ancestor "$__dobius_name"',
    'done',
    'if [ -n "$DOBIUS_AGENT_HOOK_ENDPOINT" ] && [ -r "$DOBIUS_AGENT_HOOK_ENDPOINT" ]; then',
    '  __dobius_fill_from_endpoint_file "$DOBIUS_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# DOBIUS_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$DOBIUS_AGENT_HOOK_TOKEN" ] && [ -n "$DOBIUS_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/dobius-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/dobius-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dobius-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dobius-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/dobius/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/dobius/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^DOBIUS_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$DOBIUS_AGENT_HOOK_PORT" ]; then',
    '      __dobius_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$DOBIUS_AGENT_HOOK_PORT" ] || [ -z "$DOBIUS_AGENT_HOOK_TOKEN" ] || [ -z "$DOBIUS_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    'payload=$(cat)',
    'if [ -z "$payload" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${DOBIUS_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Dobius-Agent-Hook-Token: ${DOBIUS_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${DOBIUS_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${DOBIUS_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${DOBIUS_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${DOBIUS_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${DOBIUS_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${DOBIUS_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
